name: build_node_compilers
version: 0.3.2
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  bazel_worker: ^1.0.1
  build: ^2.2.1
  build_config: ^1.0.0
  build_modules: ^4.0.4
  collection: ^1.15.0
  crypto: ^3.0.1
  logging: ^1.0.2
  meta: ^1.1.0
  node_preamble: ^2.0.1
  path: ^1.4.2
  pool: ^1.3.6
  scratch_space: ^1.0.1

dev_dependencies:
  build_test: ^2.1.5
  pedantic: ^1.0.0
  test: ^1.20.1
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
