name: node_interop
description: Provides Dart bindings and utility functions for core Node.js modules.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  test: ^1.20.1
  build_runner: any
  build_node_compilers:
    path: ../build_node_compilers
  build_test: ^2.1.5
